# Generated by Django 4.2.6 on 2023-11-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_senaempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], max_length=2)),
                ('num_documento', models.CharField(max_length=20)),
                ('fecha_expedicion', models.DateField()),
                ('lugar_expedicion', models.CharField(max_length=255)),
                ('nombre_tecnologo', models.CharField(max_length=100)),
                ('ficha_tecnologo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('ocupacion', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha_expedicion', models.DateField()),
                ('lugar_expedicion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_expedicion', models.DateField(auto_now_add=True)),
                ('lugar_expedicion', models.TextField()),
                ('asunto', models.TextField()),
                ('id_aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.aprendiz')),
                ('id_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.instructor')),
                ('id_sena_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.senaempresa')),
            ],
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='id_certificado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.certificado'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='id_rol_sena_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.rolsenaempresa'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='id_sena_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.senaempresa'),
        ),
    ]
