# Generated by Django 4.2.6 on 2023-11-27 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_aprendiz_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='id_certificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.certificado'),
        ),
    ]
